#input("Hello, Which city did you grow in? ")
#input("Hello what is the name of your pet? ")
#input("Your name ")
print("Hello " + input("Your name ")+" "+",Welcome to your Band name Generator!")
city=input("Which city did you grow in? ")
print(city)
pet=input("What is the name of your pet? ")
print(pet)
band_name=("You might call your band "+ city + pet)
print(band_name)
print("Thank you for using Band name Generator")